### PR TITLE
Added Interior Expansion

### PR DESCRIPTION
**Pull request by dmadisetti**
Added interior expansion, and some tests.

### CODE REVIEW

**Review by matthias-baer — APPROVED** [review]
Changes look good. Can be merged.

Thanks!

**Review by matthias-baer — APPROVED** [review]

**Review by matthias-baer — APPROVED** [review]
Hmm.... I select "Approve", but github saves it as a comment only. Something wrong with github at the moment?

**Comment by maroba** [comment]
> Hmm.... I select "Approve", but github saves it as a comment only. Something wrong with github at the moment?

LOL, I was using the wrong account.

**Comment by dmadisetti** [comment]
Thanks!

**Pull request merged**
